### ISSUE TITLE
Write Pressbooks.org blog post about Shapeshifter feature:

### ISSUE THREAD

**Issue by connerbw** [pressbooks/docs#39]
Write Pressbooks.org blog post about how to use new Shapeshifter feature if an open source developer wants to try it. 

Diffs in question:

+ https://github.com/pressbooks/pressbooks/commit/944809cabb4a542dfe6d21ee7a0942ae8408d73d

+ https://github.com/pressbooks/pressbooks-book/commit/26b155db334ceb82bc7856ed312dce6223f70b12

**Comment by connerbw** [comment]
# Font Selector Theme Option

When users choose a new theme in Pressbooks, they often would like to keep the design, but want a different typeface that’s either part of a different theme, or not currently part of any of our supported themes. They might also wish to use one typeface in the webbook version of the book and another in the PDF (print) export.

Normally we just laugh our loud because we can't have amateurs ruining our beautiful books with their questionable typography choices but then someone said: What if I gave you money?

Enter Shape Shifter! A nerdy code name for theme options that allows book administrators to choose from a curated list of typefaces for Headers and Body text for webbooks, PDF exports, and ebooks separately.

[In a previous sprint](https://github.com/orgs/pressbooks/projects/43), we've added the code to do this in [Pressbooks](https://github.com/pressbooks/pressbooks/pull/1792) and [McLuhan](https://github.com/pressbooks/pressbooks-book/pull/602). We're rolling out the feature for EDU customers in a premium theme called Malala. Open source users get this blog post! Developers who want to take advantage of this feature need to convert their [Global Typography](https://github.com/pressbooks/pressbooks/blob/dev/inc/class-globaltypography.php) SCSS. 

Here's how it could be done for [Clarke.](https://github.com/pressbooks/pressbooks-clarke/blob/8a87708bd9a8be712e3dcba39007eeac2f5cb8cb/assets/styles/web/_fonts.scss#L1)

Before:

```scss
@import 'font-stack-web'; 
$serif-web: serif !default;
$sans-serif-web: sans-serif !default;

$font-1: 'Times New Roman', Georgia, $serif-web;
$font-2: Helvetica, Arial, $sans-serif-web;
$font-3: $font-2;
```

After:

```scss
// Load dynamically generated Global Typography fonts
@import 'font-stack-web'; 
$serif-web: serif !default;
$sans-serif-web: sans-serif !default;

// Load Shape Shifter fonts, if any. Must come after Global Typography snippet
@import 'shapeshifter-font-stack-web';
$shapeshifter-font-1-is-serif: true !default;
$shapeshifter-font-2-is-serif: true !default;

// Insert custom fonts for your theme into the font stacks below. Always end the
// stack with $serif-web or $sans-serif-web, as appropriate—this allows custom
// language support to be added dynamically.

@if variable-exists(shapeshifter-font-1) {
  $font-1: $shapeshifter-font-1, if($shapeshifter-font-1-is-serif, $serif-web, $sans-serif-web);
} @else {
  $font-1: 'Times New Roman', Georgia, $serif-web;    
}
@if variable-exists(shapeshifter-font-2) {
  $font-2: $shapeshifter-font-2, if($shapeshifter-font-2-is-serif, $serif-web, $sans-serif-web);
} @else {
  $font-2: Helvetica, Arial, $sans-serif-web;  
}
$font-3: $font-2;
```

Make changes like the above to:

 + `assets/styles/epub/_fonts.scss`
 + `assets/styles/epub/_fonts.scss`
 + `assets/styles/prince/_fonts.scss` 

Pay special attention to variable names _(replace $sans-serif-web to $sans-serif-epub or $sans-serif-prince, for example)_ If you have `@import` statements move them from the bottom of the file into the `else` conditions. 

To finish, add this code snippet in your theme's `functions.php` file:

```php
add_filter('pb_is_shape_shifter_compatible', '__return_true');
```
Once activated, the theme should have new Theme Options for each format:

![Shape Shifter Feature](https://user-images.githubusercontent.com/812192/65540647-cb349080-ded9-11e9-976e-96ec2aca0dd5.png)

> "90 percent of design is typography. And the other 90 percent is whitespace"
